@token = f066b90c065106db9d77

POST http://localhost:8080/reservation
Authorization: {{token}}
Content-Type: application/json

{
    "user": "user1",
    "startDate": "startDate",
    "endDate":"endDate",
    "room": "someRoom"
}
###

GET http://localhost:8080/reservation/eb2bc607be4e21fd9903
Authorization: {{token}}
###

GET http://localhost:8080/reservation/all
Authorization: {{token}}
###

PUT http://localhost:8080/reservation/eb2bc607be4e21fd9903
Authorization: {{token}}
Content-Type: application/json

{
    "room": "someOtherRoom",
    "user": "user2"

}
###